# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingscalculator', '0002_remove_calculator_initial_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='initial_capital',
            field=models.IntegerField(default=0),
        ),
    ]
