# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingscalculator', '0003_calculator_initial_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='initial_capital',
            field=models.IntegerField(verbose_name='Initial Capital'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='interest_rate',
            field=models.IntegerField(verbose_name='Interest rate (annual)'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='number_of_years',
            field=models.IntegerField(verbose_name='Number of Years'),
        ),
    ]
