# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingscalculator', '0005_auto_20170124_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='interest_rate',
            field=models.FloatField(default=3.5, verbose_name='Interest rate (annual)'),
        ),
    ]
