# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingscalculator', '0006_auto_20170124_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='initial_capital',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='interest_rate',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='number_of_years',
            field=models.IntegerField(default=5),
        ),
    ]
