# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingscalculator', '0007_auto_20170127_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='interest_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='number_of_years',
            field=models.IntegerField(),
        ),
    ]
