# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingscalculator', '0008_auto_20170127_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='initial_capital',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='interest_rate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='number_of_years',
            field=models.CharField(max_length=200),
        ),
    ]
